services:
    grafana-lgtm:
        image: "grafana/otel-lgtm:latest"
        ports:
            - "3000:3000"
            - "4317"
            - "4318"
    postgres:
        image: "postgres:latest"
        environment:
            - "POSTGRES_DB=ledgerx"
            - "POSTGRES_PASSWORD=ledgerx"
            - "POSTGRES_USER=ledgerx"
        ports:
            - "5432"
    rabbitmq:
        image: "rabbitmq:latest"
        environment:
            - "RABBITMQ_DEFAULT_PASS=ledgerx"
            - "RABBITMQ_DEFAULT_USER=ledgerx"
        ports:
            - "5672"
