services:
    ledgerx:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - "DB_HOST=postgres"
            - "DB_PORT=5432"
            - "DB_NAME=ledgerx"
            - "DB_USER=ledgerx"
            - "DB_PASSWORD=ledgerx"
            - "DB_SSLMODE=require"
            - "RABBITMQ_HOST=rabbitmq"
            - "RABBITMQ_PORT=5672"
            - "RABBITMQ_USER=ledgerx"
            - "RABBITMQ_PASSWORD=ledgerx"
        ports:
            - "25360:8080"
        depends_on:
            postgres:
                condition: service_healthy
            rabbitmq:
                condition: service_started
    grafana-lgtm:
        image: "grafana/otel-lgtm:latest"
        ports:
            - "3000:3000"
            - "4317"
            - "4318"
    postgres:
        build:
            context: ./docker/postgres
            dockerfile: Dockerfile
        environment:
            - "POSTGRES_DB=ledgerx"
            - "POSTGRES_PASSWORD=ledgerx"
            - "POSTGRES_USER=ledgerx"
        ports:
            - "5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ledgerx -d ledgerx"]
            interval: 10s
            timeout: 5s
            retries: 5
    rabbitmq:
        image: "rabbitmq:latest"
        environment:
            - "RABBITMQ_DEFAULT_PASS=ledgerx"
            - "RABBITMQ_DEFAULT_USER=ledgerx"
        ports:
            - "5672"
