package br.com.nischor.ledgerxbackend.accounting.application.dto;

import br.com.nischor.ledgerxbackend.accounting.domain.model.RecurrenceFrequency;
import br.com.nischor.ledgerxbackend.accounting.domain.model.TransactionType;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.UUID;

/**
 * Application-layer data transfer object representing a recurring transaction rule.
 *
 * @param id the recurring transaction rule identifier
 * @param companyId the identifier of the company that owns the rule
 * @param financialAccountId the identifier of the financial account the generated transactions apply to
 * @param categoryId the identifier of the category the generated transactions belong to
 * @param type the transaction type (income or expense) generated by the rule
 * @param amount the amount generated for each occurrence
 * @param description the description applied to generated transactions
 * @param frequency how often the rule recurs
 * @param nextOccurrence the date on which the next transaction is due to be generated
 * @param active whether the rule is currently active
 */
public record RecurringTransactionRuleDto(UUID id, UUID companyId, UUID financialAccountId, UUID categoryId,
        TransactionType type, BigDecimal amount, String description, RecurrenceFrequency frequency,
        LocalDate nextOccurrence, boolean active) {
}
