package br.com.nischor.ledgerxbackend.accounting.interfaces.rest.dto;

import br.com.nischor.ledgerxbackend.accounting.domain.model.RecurrenceFrequency;
import br.com.nischor.ledgerxbackend.accounting.domain.model.TransactionType;
import jakarta.validation.constraints.FutureOrPresent;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.Size;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.UUID;

/**
 * REST request payload for creating a recurring transaction rule.
 *
 * @param financialAccountId the identifier of the financial account the generated transactions apply to
 * @param categoryId the identifier of the category the generated transactions belong to
 * @param type the transaction type (income or expense) generated by the rule
 * @param amount the amount generated for each occurrence; must be strictly positive
 * @param description the description applied to generated transactions; up to 255 characters
 * @param frequency how often the rule recurs
 * @param firstOccurrence the date of the first occurrence; must not be in the past
 */
public record CreateRecurringTransactionRuleRequest(
        @NotNull UUID financialAccountId,
        @NotNull UUID categoryId,
        @NotNull TransactionType type,
        @NotNull @Positive BigDecimal amount,
        @Size(max = 255) String description,
        @NotNull RecurrenceFrequency frequency,
        @NotNull @FutureOrPresent(message = "firstOccurrence cannot be in the past") LocalDate firstOccurrence) {
}
