package br.com.nischor.ledgerxbackend.accounting.application.usecase;

import br.com.nischor.ledgerxbackend.accounting.application.dto.RecurringTransactionRuleDto;
import br.com.nischor.ledgerxbackend.accounting.application.mapper.RecurringTransactionRuleMapper;
import br.com.nischor.ledgerxbackend.accounting.domain.model.Category;
import br.com.nischor.ledgerxbackend.accounting.domain.model.RecurrenceFrequency;
import br.com.nischor.ledgerxbackend.accounting.domain.model.RecurringTransactionRule;
import br.com.nischor.ledgerxbackend.accounting.domain.model.TransactionType;
import br.com.nischor.ledgerxbackend.accounting.domain.repository.CategoryRepository;
import br.com.nischor.ledgerxbackend.accounting.domain.repository.RecurringTransactionRuleRepository;
import br.com.nischor.ledgerxbackend.shared.domain.exception.BusinessRuleViolationException;
import br.com.nischor.ledgerxbackend.shared.domain.exception.EntityNotFoundException;
import br.com.nischor.ledgerxbackend.shared.domain.valueobject.Money;
import java.time.LocalDate;
import java.util.UUID;
import org.springframework.stereotype.Service;

/**
 * Creates a new recurring transaction rule used to automatically generate transactions on a schedule.
 */
@Service
public class CreateRecurringTransactionRuleUseCase {

    private final RecurringTransactionRuleRepository recurringTransactionRuleRepository;
    private final CategoryRepository categoryRepository;
    private final RecurringTransactionRuleMapper mapper;

    /**
     * Creates the use case.
     *
     * @param recurringTransactionRuleRepository repository used to persist the rule
     * @param categoryRepository repository used to look up the target category
     * @param mapper mapper used to convert the saved rule into a DTO
     */
    public CreateRecurringTransactionRuleUseCase(
            RecurringTransactionRuleRepository recurringTransactionRuleRepository,
            CategoryRepository categoryRepository, RecurringTransactionRuleMapper mapper) {
        this.recurringTransactionRuleRepository = recurringTransactionRuleRepository;
        this.categoryRepository = categoryRepository;
        this.mapper = mapper;
    }

    /**
     * Creates a recurring transaction rule that generates transactions on the given schedule.
     *
     * @param companyId the identifier of the company the rule belongs to
     * @param financialAccountId the identifier of the financial account the generated transactions apply to
     * @param categoryId the identifier of the category the generated transactions belong to
     * @param type the transaction type (income or expense) generated by the rule
     * @param amount the amount generated for each occurrence
     * @param description the description applied to generated transactions
     * @param frequency how often the rule recurs
     * @param firstOccurrence the date of the first occurrence
     * @return the created recurring transaction rule as a DTO
     * @throws EntityNotFoundException if no category exists with the given identifier
     * @throws BusinessRuleViolationException if the category's type does not match the rule's transaction type
     */
    public RecurringTransactionRuleDto execute(UUID companyId, UUID financialAccountId, UUID categoryId,
            TransactionType type, Money amount, String description, RecurrenceFrequency frequency,
            LocalDate firstOccurrence) {
        var category = categoryRepository.findById(categoryId)
                .orElseThrow(() -> new EntityNotFoundException(Category.class, categoryId));

        if (category.getType() != type) {
            throw new BusinessRuleViolationException(
                    "Category '%s' is a %s category and cannot be used for a %s recurring rule"
                            .formatted(category.getName(), category.getType(), type));
        }

        var rule = new RecurringTransactionRule(UUID.randomUUID(), companyId, financialAccountId, categoryId, type,
                amount, description, frequency, firstOccurrence);
        return mapper.toDto(recurringTransactionRuleRepository.save(rule));
    }
}
