package br.com.nischor.ledgerxbackend.accounting.application.usecase;

import br.com.nischor.ledgerxbackend.accounting.application.dto.TransactionDto;
import br.com.nischor.ledgerxbackend.accounting.domain.repository.RecurringTransactionRuleRepository;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;
import org.springframework.stereotype.Service;

/**
 * Materializes every {@code RecurringTransactionRule} that is due (BR-113) into a real
 * {@code Transaction}, delegating to {@link RecordTransactionUseCase} so the same validation and
 * balance-update logic used for manually recorded transactions applies here too. Each processed
 * rule is then advanced to its next occurrence per its {@code frequency}.
 */
@Service
public class GenerateDueRecurringTransactionsUseCase {

    private final RecurringTransactionRuleRepository recurringTransactionRuleRepository;
    private final RecordTransactionUseCase recordTransactionUseCase;

    /**
     * Creates the use case.
     *
     * @param recurringTransactionRuleRepository repository used to look up active rules and persist their
     *         advanced state
     * @param recordTransactionUseCase use case used to record the transaction generated by each due rule
     */
    public GenerateDueRecurringTransactionsUseCase(
            RecurringTransactionRuleRepository recurringTransactionRuleRepository,
            RecordTransactionUseCase recordTransactionUseCase) {
        this.recurringTransactionRuleRepository = recurringTransactionRuleRepository;
        this.recordTransactionUseCase = recordTransactionUseCase;
    }

    /**
     * Finds every active recurring transaction rule of the given company that is due today, records the
     * corresponding transaction for each one, and advances the rule to its next occurrence.
     *
     * @param companyId the identifier of the company whose rules should be processed
     * @return the list of transactions generated from due rules, as DTOs
     */
    public List<TransactionDto> execute(UUID companyId) {
        var today = LocalDate.now();
        var dueRules = recurringTransactionRuleRepository.findAllByCompanyIdAndActiveTrue(companyId).stream()
                .filter(rule -> rule.isDue(today))
                .toList();

        return dueRules.stream().map(rule -> {
            var transaction = recordTransactionUseCase.execute(rule.getFinancialAccountId(), rule.getCategoryId(),
                    rule.getType(), rule.getAmount(), rule.getDescription(), rule.getNextOccurrence());
            rule.advance();
            recurringTransactionRuleRepository.save(rule);
            return transaction;
        }).toList();
    }
}
