package br.com.nischor.ledgerxbackend.accounting.infrastructure.persistence.entity;

import br.com.nischor.ledgerxbackend.accounting.domain.model.RecurrenceFrequency;
import br.com.nischor.ledgerxbackend.accounting.domain.model.TransactionType;
import br.com.nischor.ledgerxbackend.shared.infrastructure.persistence.AuditableEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.UUID;

/**
 * JPA entity persisting a {@code RecurringTransactionRule} to the {@code recurring_transaction_rules} table.
 */
@Entity
@Table(name = "recurring_transaction_rules")
public class RecurringTransactionRuleJpaEntity extends AuditableEntity {

    @Column(nullable = false)
    private UUID companyId;

    @Column(nullable = false)
    private UUID financialAccountId;

    @Column(nullable = false)
    private UUID categoryId;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private TransactionType type;

    @Column(nullable = false, precision = 19, scale = 2)
    private BigDecimal amount;

    @Column(nullable = false)
    private String currencyCode;

    @Column(nullable = false)
    private String description;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private RecurrenceFrequency frequency;

    @Column(nullable = false)
    private LocalDate nextOccurrence;

    @Column(nullable = false)
    private boolean active = true;

    /**
     * Protected no-args constructor required by JPA.
     */
    protected RecurringTransactionRuleJpaEntity() {
    }

    /**
     * Creates a new active recurring transaction rule entity.
     *
     * @param id the recurring transaction rule identifier
     * @param companyId the identifier of the company that owns the rule
     * @param financialAccountId the identifier of the financial account the generated transactions apply to
     * @param categoryId the identifier of the category the generated transactions belong to
     * @param type the transaction type (income or expense) generated by the rule
     * @param amount the amount generated for each occurrence
     * @param currencyCode the ISO currency code of the amount
     * @param description the description applied to generated transactions
     * @param frequency how often the rule recurs
     * @param nextOccurrence the date on which the next transaction is due to be generated
     */
    public RecurringTransactionRuleJpaEntity(UUID id, UUID companyId, UUID financialAccountId, UUID categoryId,
            TransactionType type, BigDecimal amount, String currencyCode, String description,
            RecurrenceFrequency frequency, LocalDate nextOccurrence) {
        super(id);
        this.companyId = companyId;
        this.financialAccountId = financialAccountId;
        this.categoryId = categoryId;
        this.type = type;
        this.amount = amount;
        this.currencyCode = currencyCode;
        this.description = description;
        this.frequency = frequency;
        this.nextOccurrence = nextOccurrence;
    }

    /**
     * Returns the identifier of the company that owns the rule.
     *
     * @return the company identifier
     */
    public UUID getCompanyId() {
        return companyId;
    }

    /**
     * Returns the identifier of the financial account the generated transactions apply to.
     *
     * @return the financial account identifier
     */
    public UUID getFinancialAccountId() {
        return financialAccountId;
    }

    /**
     * Returns the identifier of the category the generated transactions belong to.
     *
     * @return the category identifier
     */
    public UUID getCategoryId() {
        return categoryId;
    }

    /**
     * Returns the transaction type generated by the rule.
     *
     * @return the transaction type
     */
    public TransactionType getType() {
        return type;
    }

    /**
     * Returns the amount generated for each occurrence.
     *
     * @return the transaction amount
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * Returns the ISO currency code of the amount.
     *
     * @return the currency code
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * Returns the description applied to generated transactions.
     *
     * @return the transaction description
     */
    public String getDescription() {
        return description;
    }

    /**
     * Returns how often the rule recurs.
     *
     * @return the recurrence frequency
     */
    public RecurrenceFrequency getFrequency() {
        return frequency;
    }

    /**
     * Returns the date on which the next transaction is due to be generated.
     *
     * @return the next occurrence date
     */
    public LocalDate getNextOccurrence() {
        return nextOccurrence;
    }

    /**
     * Returns whether the rule is currently active.
     *
     * @return {@code true} if the rule is active, {@code false} otherwise
     */
    public boolean isActive() {
        return active;
    }

    /**
     * Sets whether the rule is currently active.
     *
     * @param active the new active state
     */
    public void setActive(boolean active) {
        this.active = active;
    }
}
