package br.com.nischor.ledgerxbackend.accounting.domain.model;

import br.com.nischor.ledgerxbackend.shared.domain.valueobject.Money;
import java.time.LocalDate;
import java.util.UUID;

/**
 * Domain entity representing a rule that automatically generates a transaction on a recurring schedule until
 * it is deactivated.
 */
public class RecurringTransactionRule {

    private final UUID id;
    private final UUID companyId;
    private final UUID financialAccountId;
    private final UUID categoryId;
    private final TransactionType type;
    private final Money amount;
    private final String description;
    private final RecurrenceFrequency frequency;
    /** The date on which the next transaction is due to be generated. */
    private LocalDate nextOccurrence;
    /** Whether the rule is currently active. */
    private boolean active;

    /**
     * Creates a new active recurring transaction rule.
     *
     * @param id the recurring transaction rule identifier
     * @param companyId the identifier of the company that owns the rule
     * @param financialAccountId the identifier of the financial account the generated transactions apply to
     * @param categoryId the identifier of the category the generated transactions belong to
     * @param type the transaction type (income or expense) generated by the rule
     * @param amount the amount generated for each occurrence
     * @param description the description applied to generated transactions
     * @param frequency how often the rule recurs
     * @param nextOccurrence the date of the first (and initially next) occurrence
     */
    public RecurringTransactionRule(UUID id, UUID companyId, UUID financialAccountId, UUID categoryId,
            TransactionType type, Money amount, String description, RecurrenceFrequency frequency,
            LocalDate nextOccurrence) {
        this.id = id;
        this.companyId = companyId;
        this.financialAccountId = financialAccountId;
        this.categoryId = categoryId;
        this.type = type;
        this.amount = amount;
        this.description = description;
        this.frequency = frequency;
        this.nextOccurrence = nextOccurrence;
        this.active = true;
    }

    /**
     * Determines whether the rule is active and its next occurrence date has arrived or passed.
     *
     * @param today the date to check the rule against
     * @return {@code true} if the rule is active and due, {@code false} otherwise
     */
    public boolean isDue(LocalDate today) {
        return active && !nextOccurrence.isAfter(today);
    }

    /**
     * Advances the next occurrence date by one unit of the rule's {@link RecurrenceFrequency}.
     */
    public void advance() {
        this.nextOccurrence = switch (frequency) {
            case WEEKLY -> nextOccurrence.plusWeeks(1);
            case MONTHLY -> nextOccurrence.plusMonths(1);
            case YEARLY -> nextOccurrence.plusYears(1);
        };
    }

    /**
     * Marks the rule as inactive.
     */
    public void deactivate() {
        this.active = false;
    }

    /**
     * Returns the recurring transaction rule identifier.
     *
     * @return the rule identifier
     */
    public UUID getId() {
        return id;
    }

    /**
     * Returns the identifier of the company that owns the rule.
     *
     * @return the company identifier
     */
    public UUID getCompanyId() {
        return companyId;
    }

    /**
     * Returns the identifier of the financial account the generated transactions apply to.
     *
     * @return the financial account identifier
     */
    public UUID getFinancialAccountId() {
        return financialAccountId;
    }

    /**
     * Returns the identifier of the category the generated transactions belong to.
     *
     * @return the category identifier
     */
    public UUID getCategoryId() {
        return categoryId;
    }

    /**
     * Returns the transaction type generated by the rule.
     *
     * @return the transaction type
     */
    public TransactionType getType() {
        return type;
    }

    /**
     * Returns the amount generated for each occurrence.
     *
     * @return the transaction amount
     */
    public Money getAmount() {
        return amount;
    }

    /**
     * Returns the description applied to generated transactions.
     *
     * @return the transaction description
     */
    public String getDescription() {
        return description;
    }

    /**
     * Returns how often the rule recurs.
     *
     * @return the recurrence frequency
     */
    public RecurrenceFrequency getFrequency() {
        return frequency;
    }

    /**
     * Returns the date on which the next transaction is due to be generated.
     *
     * @return the next occurrence date
     */
    public LocalDate getNextOccurrence() {
        return nextOccurrence;
    }

    /**
     * Returns whether the rule is currently active.
     *
     * @return {@code true} if the rule is active, {@code false} otherwise
     */
    public boolean isActive() {
        return active;
    }
}
